/**
 * Keep in sync with apps/api/src/common/known-syndication-outlets.ts
 */
export const KNOWN_SYNDICATION_OUTLET_LABELS: readonly string[] = [
  'Brisbane Times',
  'Sydney Morning Herald',
  'The Age',
  'WAtoday',
  'Perth Now',
  'Canberra Times',
  'The Australian',
  'Fairfax Media',
  'nine.com.au',
  'BBC News',
  'The Guardian',
  'Daily Mail',
  'The Telegraph',
  'The Independent',
  'Reuters',
  'Associated Press',
  'AP News',
  'AFP',
  'CNN',
  'Fox News',
  'The New York Times',
  'Washington Post',
  'Bloomberg',
  'Times of India',
  'TIMESOFINDIA.COM',
  'Hindustan Times',
  'NDTV',
  'India Today',
  'indiatoday.in',
  'The Hindu',
  'Indian Express',
  'News18',
  'Zee News',
  'Aaj Tak',
  'Dainik Bhaskar',
  'Amar Ujala',
  'Dainik Jagran',
  'Navbharat Times',
  'Rajasthan Patrika',
  'Patrika',
  'Jansatta',
  'Live Hindustan',
  'India TV',
  'Anandabazar Patrika',
  'Eenadu',
  'Lokmat',
  'Sakal',
  'Sandesh',
  'Jagbani',
  'ANI',
  'PTI',
  'IANS',
  'UNI',
  'Le Figaro',
  'Le Monde',
  'Der Spiegel',
  'Bild',
  'El País',
  'La Repubblica',
  'Deutsche Welle',
  'Al Jazeera',
  'Gulf News',
  'Khaleej Times',
  'Hurriyet',
  'TRT Haber',
  'G1 Globo',
  'News24',
];
